package com.mycompany.proyectsurvival;

import Entities_Resources_Shelter.Crab;
import Entities_Resources_Shelter.Crocodiles;
import Entities_Resources_Shelter.Deer;
import Entities_Resources_Shelter.Fruit;
import Entities_Resources_Shelter.Jaguar;
import Entities_Resources_Shelter.Mushrooms;
import Entities_Resources_Shelter.Resource;
import Entities_Resources_Shelter.Rocks;
import Entities_Resources_Shelter.Shelter;
import Entities_Resources_Shelter.Snake;
import Entities_Resources_Shelter.Tree;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import General_Threads.ThreadDays;

/**
 *
 * @author david
 */
public class Menu extends javax.swing.JPanel {
    int pos_x, pos_y;
    public ArrayList character_list;
    public ArrayList<Resource> inventory;
    public Shelter shelter;
    public GamePanel gp;
    
    private String[] Actions_Explorer;
    private String[] Actions_Hunter;
    private String[] Actions_Gatherer;
    private String[] Actions_Builder;
    private String[] Actions_Medic;
    private String[] Actions_Scientist;
    
    
    private String[][] Actions_LIST;
    public DefaultComboBoxModel Actions_Selected;
    
    public Menu(GamePanel gp) {
        this.gp = gp;
        
        this.setFocusable(true);
        
        this.Actions_Explorer = new String[] {"Explor", "Move","Change Shelter"};
        this.Actions_Hunter = new String[] {"Hunt", "Protect","Move" ,"Change Shelter"};
        this.Actions_Gatherer = new String[] {"Gather","Move" ,"Change Shelter"};
        this.Actions_Builder = new String[] {"Build", "Repair","Move" ,"Change Shelter", "Creat Tool"};
        this.Actions_Medic = new String[] {"Heal", "Creat Potion" , "Move", "Change Shelter"};
        this.Actions_Scientist = new String[] {"Creat Tool", "Creat Potion" , "Move", "Change Shelter"};
        
        this.Actions_LIST = new String[][] {Actions_Explorer,Actions_Hunter,Actions_Gatherer,Actions_Builder,Actions_Medic,Actions_Scientist};
        this.Actions_Selected = this.setActions(0);
        
        
    
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_HEARTH1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        Rest_Button = new javax.swing.JButton();
        BOXSelectedCharacter = new javax.swing.JComboBox<>();
        HealthBar = new javax.swing.JProgressBar();
        StaminaBar = new javax.swing.JProgressBar();
        Label_pos = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Journal = new java.awt.TextArea();
        jLabel_HEARTH = new javax.swing.JLabel();
        jLabel_HEARTH2 = new javax.swing.JLabel();
        jLabel_Shelter = new javax.swing.JLabel();
        jLabel_Char = new javax.swing.JLabel();
        jLabel_FRUITS = new javax.swing.JLabel();
        jLabel_MEAT = new javax.swing.JLabel();
        jLabel_WOOD = new javax.swing.JLabel();
        jLabel_MUSHROOMS = new javax.swing.JLabel();
        jLabel_POTIONS = new javax.swing.JLabel();
        jLabel_ROCKS = new javax.swing.JLabel();
        jLabel_TOOLS = new javax.swing.JLabel();
        DO_Button = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton_Insert = new javax.swing.JButton();
        jComboBox_InsertAsset = new javax.swing.JComboBox<>();
        jLabel_Objective = new javax.swing.JLabel();
        lbl_days = new javax.swing.JLabel();
        text_days = new javax.swing.JTextField();
        btn_increase_days = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_events = new javax.swing.JLabel();
        cbx_events = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_durationDays = new javax.swing.JTextPane();
        lbl_durationdays = new javax.swing.JLabel();
        btn_provoke = new javax.swing.JButton();
        lbl_durationdays1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        msg_Actions = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        jLabel_HEARTH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hearth.png"))); // NOI18N
        jLabel_HEARTH1.setDoubleBuffered(true);
        jLabel_HEARTH1.setMaximumSize(new java.awt.Dimension(17, 17));
        jLabel_HEARTH1.setMinimumSize(new java.awt.Dimension(17, 17));
        jLabel_HEARTH1.setPreferredSize(new java.awt.Dimension(17, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proyect [Island Survivors]", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DialogInput", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(640, 570));
        setMinimumSize(new java.awt.Dimension(340, 570));
        setPreferredSize(new java.awt.Dimension(390, 570));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        Rest_Button.setText("REST");
        Rest_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rest_ButtonActionPerformed(evt);
            }
        });

        BOXSelectedCharacter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Explorer", "Hunter", "Gatherer", "Builder", "Medic", "Scientist"}));
        BOXSelectedCharacter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BOXSelectedCharacterItemStateChanged(evt);
            }
        });
        BOXSelectedCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOXSelectedCharacterActionPerformed(evt);
            }
        });

        HealthBar.setBackground(new java.awt.Color(0, 0, 0));
        HealthBar.setForeground(new java.awt.Color(255, 255, 255));
        HealthBar.setValue(100);
        HealthBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        StaminaBar.setBackground(new java.awt.Color(0, 0, 0));
        StaminaBar.setForeground(new java.awt.Color(255, 255, 255));
        StaminaBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Label_pos.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        Label_pos.setForeground(new java.awt.Color(255, 255, 255));
        Label_pos.setText("(0, 0)");

        jComboBox1.setModel(this.setActions(this.BOXSelectedCharacter.getSelectedIndex()));

        Journal.setEditable(false);

        jLabel_HEARTH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hearth.png"))); // NOI18N
        jLabel_HEARTH.setDoubleBuffered(true);
        jLabel_HEARTH.setMaximumSize(new java.awt.Dimension(17, 17));
        jLabel_HEARTH.setMinimumSize(new java.awt.Dimension(17, 17));
        jLabel_HEARTH.setPreferredSize(new java.awt.Dimension(17, 17));

        jLabel_HEARTH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stomach.png"))); // NOI18N
        jLabel_HEARTH2.setDoubleBuffered(true);
        jLabel_HEARTH2.setMaximumSize(new java.awt.Dimension(17, 17));
        jLabel_HEARTH2.setMinimumSize(new java.awt.Dimension(17, 17));
        jLabel_HEARTH2.setPreferredSize(new java.awt.Dimension(17, 17));

        jLabel_Shelter.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Shelter.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Shelter.setText("Shelter");

        jLabel_Char.setBackground(new java.awt.Color(255, 51, 51));
        jLabel_Char.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Char.setText("jLabel3");
        jLabel_Char.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel_Char.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel_Char.setPreferredSize(new java.awt.Dimension(42, 42));

        jLabel_FRUITS.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_FRUITS.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FRUITS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fruits.PNG"))); // NOI18N
        jLabel_FRUITS.setText("FRUITS...");
        jLabel_FRUITS.setDoubleBuffered(true);
        jLabel_FRUITS.setMaximumSize(new java.awt.Dimension(125, 17));
        jLabel_FRUITS.setMinimumSize(new java.awt.Dimension(125, 17));
        jLabel_FRUITS.setOpaque(true);
        jLabel_FRUITS.setPreferredSize(new java.awt.Dimension(125, 17));
        jLabel_FRUITS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_FRUITSMouseClicked(evt);
            }
        });

        jLabel_MEAT.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_MEAT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MEAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meat.PNG"))); // NOI18N
        jLabel_MEAT.setText("MEAT....");
        jLabel_MEAT.setDoubleBuffered(true);
        jLabel_MEAT.setMaximumSize(new java.awt.Dimension(125, 17));
        jLabel_MEAT.setMinimumSize(new java.awt.Dimension(125, 17));
        jLabel_MEAT.setOpaque(true);
        jLabel_MEAT.setPreferredSize(new java.awt.Dimension(125, 17));
        jLabel_MEAT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MEATMouseClicked(evt);
            }
        });

        jLabel_WOOD.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_WOOD.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_WOOD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wood.PNG"))); // NOI18N
        jLabel_WOOD.setText("WOOD....");
        jLabel_WOOD.setDoubleBuffered(true);
        jLabel_WOOD.setMaximumSize(new java.awt.Dimension(125, 17));
        jLabel_WOOD.setMinimumSize(new java.awt.Dimension(125, 17));
        jLabel_WOOD.setOpaque(true);
        jLabel_WOOD.setPreferredSize(new java.awt.Dimension(125, 17));
        jLabel_WOOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_WOODMouseClicked(evt);
            }
        });

        jLabel_MUSHROOMS.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_MUSHROOMS.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MUSHROOMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroom.PNG"))); // NOI18N
        jLabel_MUSHROOMS.setText("MUSHROOMS....");
        jLabel_MUSHROOMS.setDoubleBuffered(true);
        jLabel_MUSHROOMS.setMaximumSize(new java.awt.Dimension(130, 17));
        jLabel_MUSHROOMS.setMinimumSize(new java.awt.Dimension(130, 17));
        jLabel_MUSHROOMS.setOpaque(true);
        jLabel_MUSHROOMS.setPreferredSize(new java.awt.Dimension(130, 17));
        jLabel_MUSHROOMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MUSHROOMSMouseClicked(evt);
            }
        });

        jLabel_POTIONS.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_POTIONS.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_POTIONS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/potion.PNG"))); // NOI18N
        jLabel_POTIONS.setText("POTIOINS....");
        jLabel_POTIONS.setDoubleBuffered(true);
        jLabel_POTIONS.setMaximumSize(new java.awt.Dimension(125, 17));
        jLabel_POTIONS.setMinimumSize(new java.awt.Dimension(125, 17));
        jLabel_POTIONS.setOpaque(true);
        jLabel_POTIONS.setPreferredSize(new java.awt.Dimension(125, 17));
        jLabel_POTIONS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_POTIONSMouseClicked(evt);
            }
        });

        jLabel_ROCKS.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_ROCKS.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ROCKS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rocks.PNG"))); // NOI18N
        jLabel_ROCKS.setText("ROCKS....");
        jLabel_ROCKS.setDoubleBuffered(true);
        jLabel_ROCKS.setMaximumSize(new java.awt.Dimension(125, 17));
        jLabel_ROCKS.setMinimumSize(new java.awt.Dimension(125, 17));
        jLabel_ROCKS.setOpaque(true);
        jLabel_ROCKS.setPreferredSize(new java.awt.Dimension(125, 17));
        jLabel_ROCKS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ROCKSMouseClicked(evt);
            }
        });

        jLabel_TOOLS.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_TOOLS.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TOOLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools.PNG"))); // NOI18N
        jLabel_TOOLS.setText("TOOLS....");
        jLabel_TOOLS.setDoubleBuffered(true);
        jLabel_TOOLS.setMaximumSize(new java.awt.Dimension(125, 17));
        jLabel_TOOLS.setMinimumSize(new java.awt.Dimension(125, 17));
        jLabel_TOOLS.setOpaque(true);
        jLabel_TOOLS.setPreferredSize(new java.awt.Dimension(125, 17));
        jLabel_TOOLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_TOOLSMouseClicked(evt);
            }
        });

        DO_Button.setText("DO");
        DO_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DO_ButtonActionPerformed(evt);
            }
        });

        jButton3.setText("EAT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("SHARE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton_Insert.setText("INSERT");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertActionPerformed(evt);
            }
        });

        jComboBox_InsertAsset.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tree", "Fruits", "Mushroom", "Rock", "Jaguar", "Deer", "Crabs", "Snakes", "Crocodile" }));
        jComboBox_InsertAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_InsertAssetActionPerformed(evt);
            }
        });

        jLabel_Objective.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Objective.setText("Objective....");

        lbl_days.setBackground(new java.awt.Color(0, 0, 0));
        lbl_days.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_days.setForeground(new java.awt.Color(255, 255, 255));
        lbl_days.setText("Day :");
        lbl_days.setToolTipText("");

        text_days.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        text_days.setToolTipText("");
        text_days.setAlignmentX(2.0F);
        text_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_daysActionPerformed(evt);
            }
        });

        btn_increase_days.setText("->");
        btn_increase_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_increase_daysActionPerformed(evt);
            }
        });

        lbl_events.setText("Events");

        cbx_events.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Strong Storm", "Weak Storm", "Character Accident", "Mild Illness", "Severe Illness" }));
        cbx_events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_eventsActionPerformed(evt);
            }
        });

        txt_durationDays.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(txt_durationDays);

        lbl_durationdays.setText("Duration in days");

        btn_provoke.setText("Provoke");
        btn_provoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_provokeActionPerformed(evt);
            }
        });

        lbl_durationdays1.setText(" of the storm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_events)
                        .addGap(45, 59, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_provoke))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_events, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_durationdays)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_durationdays1)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_events)
                .addGap(18, 18, 18)
                .addComponent(cbx_events, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_durationdays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_durationdays1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_provoke)
                .addGap(6, 6, 6))
        );

        msg_Actions.setColumns(20);
        msg_Actions.setRows(5);
        jScrollPane3.setViewportView(msg_Actions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Char, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_HEARTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_HEARTH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StaminaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BOXSelectedCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Shelter))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_MEAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_WOOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_FRUITS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_POTIONS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_MUSHROOMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_TOOLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_ROCKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_InsertAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_days, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(text_days, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_increase_days, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(DO_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(Rest_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_pos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Objective, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Journal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StaminaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_Char, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_HEARTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel_HEARTH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BOXSelectedCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Shelter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_MEAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Rest_Button))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DO_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ROCKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_WOOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_FRUITS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MUSHROOMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_POTIONS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_days)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_days, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_increase_days)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_TOOLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Insert)
                            .addComponent(jComboBox_InsertAsset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Journal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Objective))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Rest_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rest_ButtonActionPerformed
        
        this.gp.Selected().Order = "Rest";
        this.gp.Selected().objective = this.gp.Item_touched;
        
    }//GEN-LAST:event_Rest_ButtonActionPerformed

    private void BOXSelectedCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOXSelectedCharacterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOXSelectedCharacterActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.requestFocus();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.requestFocus();
    }//GEN-LAST:event_formMouseClicked

    private void BOXSelectedCharacterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BOXSelectedCharacterItemStateChanged
        this.jComboBox1.setModel(this.setActions(this.BOXSelectedCharacter.getSelectedIndex()));
    }//GEN-LAST:event_BOXSelectedCharacterItemStateChanged

    private void DO_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DO_ButtonActionPerformed
        this.gp.Selected().Order = jComboBox1.getSelectedItem().toString();
        this.gp.Selected().objective = this.gp.Item_touched;
        this.gp.Selected().inPosition = false;
    }//GEN-LAST:event_DO_ButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.gp.Selected().Eat();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (this.gp.Item_touched.isCharacter){
            this.gp.Selected().objective = this.gp.Item_touched;
            this.gp.Selected().Order = "Share";}
        else {this.msg_Actions.setText("You cant SHARE with "+gp.Item_touched.getString());}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertActionPerformed
        String var = this.jComboBox_InsertAsset.getSelectedItem().toString();
        switch (var) {
            case "Tree" -> gp.Trees_in_map.add(new Tree(gp)); 
            case "Fruits" -> gp.Fruits_in_map.add(new Fruit(gp));
            case "Mushroom" -> gp.Mushrooms_in_map.add(new Mushrooms(gp));
            case "Rock" -> gp.Rocks_in_map.add(new Rocks(gp));
            case "Jaguar" -> gp.animals_in_map.add(new Jaguar(gp)); 
            case "Deer" -> gp.animals_in_map.add(new Deer(gp));
            case "Crabs" -> gp.animals_in_map.add(new Crab(gp));
            case "Snakes" -> gp.animals_in_map.add(new Snake(gp));
            case "Crocodile" -> gp.animals_in_map.add(new Crocodiles(gp));          
            default -> throw new AssertionError();
        }
    }//GEN-LAST:event_jButton_InsertActionPerformed

    private void jComboBox_InsertAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_InsertAssetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_InsertAssetActionPerformed

    private void jLabel_MEATMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MEATMouseClicked
       this.resetColors();
       
       this.gp.Resource_Selected = "Meat";
       
       jLabel_MEAT.setForeground(Color.BLACK);
       jLabel_MEAT.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_MEATMouseClicked

    private void jLabel_ROCKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ROCKSMouseClicked
       this.resetColors();
       
       this.gp.Resource_Selected = "Rocks";
       
       jLabel_ROCKS.setForeground(Color.BLACK);
       jLabel_ROCKS.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_ROCKSMouseClicked

    private void jLabel_WOODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_WOODMouseClicked
       this.resetColors();
       
       this.gp.Resource_Selected = "Wood";
       
       jLabel_WOOD.setForeground(Color.BLACK);
       jLabel_WOOD.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_WOODMouseClicked

    private void jLabel_FRUITSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FRUITSMouseClicked
       this.resetColors();
       
       this.gp.Resource_Selected = "Fruits";
       
       jLabel_FRUITS.setForeground(Color.BLACK);
       jLabel_FRUITS.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_FRUITSMouseClicked

    private void jLabel_MUSHROOMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MUSHROOMSMouseClicked
       this.resetColors();
       
       this.gp.Resource_Selected = "Mushrooms";
       
       jLabel_MUSHROOMS.setForeground(Color.BLACK);
       jLabel_MUSHROOMS.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_MUSHROOMSMouseClicked

    private void jLabel_POTIONSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_POTIONSMouseClicked
       this.resetColors();
       
       this.gp.Resource_Selected = "Potions";
       
       jLabel_POTIONS.setForeground(Color.BLACK);
       jLabel_POTIONS.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_POTIONSMouseClicked

    private void jLabel_TOOLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TOOLSMouseClicked
       this.resetColors();
       
       this.gp.Resource_Selected = "Tools";
       
       jLabel_TOOLS.setForeground(Color.BLACK);
       jLabel_TOOLS.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel_TOOLSMouseClicked

    private void text_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_daysActionPerformed

    private void btn_increase_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_increase_daysActionPerformed
        // TODO add your handling code here:
        gp.timeManager.increaseDays();
    }//GEN-LAST:event_btn_increase_daysActionPerformed

    private void cbx_eventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_eventsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbx_eventsActionPerformed

    private void btn_provokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_provokeActionPerformed
        // TODO add your handling code here:
       Object selectedItem = cbx_events.getSelectedItem();
        if (selectedItem != null) {
            String selectedEvent = selectedItem.toString();
            if(selectedEvent.equals("Character Accident"))gp.generateAccident();
            else  if(selectedEvent.equals("Mild Illness") || selectedEvent.equals("Severe Illness"))gp.createIllness(selectedEvent);
            else if(selectedEvent.equals("None") || txt_durationDays.getText().equals(""));
            else
                gp.createStrom(Integer.parseInt(txt_durationDays.getText()), selectedEvent);
            txt_durationDays.setText("");
        }
    }//GEN-LAST:event_btn_provokeActionPerformed

    private DefaultComboBoxModel setActions(int i){
        return new DefaultComboBoxModel(this.Actions_LIST[i]);
    }
    
    private void resetColors(){
        jLabel_MEAT.setBackground(Color.BLACK);
        jLabel_FRUITS.setBackground(Color.BLACK);
        jLabel_WOOD.setBackground(Color.BLACK);
        jLabel_TOOLS.setBackground(Color.BLACK);
        jLabel_ROCKS.setBackground(Color.BLACK);
        jLabel_POTIONS.setBackground(Color.BLACK);
        jLabel_MUSHROOMS.setBackground(Color.BLACK);
        
        jLabel_MEAT.setForeground(Color.WHITE);
        jLabel_FRUITS.setForeground(Color.WHITE);
        jLabel_WOOD.setForeground(Color.WHITE);
        jLabel_TOOLS.setForeground(Color.WHITE);
        jLabel_ROCKS.setForeground(Color.WHITE);
        jLabel_POTIONS.setForeground(Color.WHITE);
        jLabel_MUSHROOMS.setForeground(Color.WHITE);
    
    }
    
    public void SetActionShelter(){
        
       if (gp.Item_touched.getString() != "Shelter"){
           System.out.println(" Object selected is not a shelter");
       } else { 
           this.gp.Selected().getShelter().RemoveCharacter(gp.Selected());       
            this.gp.Selected().setShelter((Shelter)gp.Item_touched);
       }
    
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> BOXSelectedCharacter;
    private javax.swing.JButton DO_Button;
    public javax.swing.JProgressBar HealthBar;
    public java.awt.TextArea Journal;
    public javax.swing.JLabel Label_pos;
    private javax.swing.JButton Rest_Button;
    public javax.swing.JProgressBar StaminaBar;
    private javax.swing.JButton btn_increase_days;
    private javax.swing.JButton btn_provoke;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbx_events;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public javax.swing.JButton jButton_Insert;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jComboBox_InsertAsset;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel_Char;
    public javax.swing.JLabel jLabel_FRUITS;
    private javax.swing.JLabel jLabel_HEARTH;
    private javax.swing.JLabel jLabel_HEARTH1;
    private javax.swing.JLabel jLabel_HEARTH2;
    public javax.swing.JLabel jLabel_MEAT;
    public javax.swing.JLabel jLabel_MUSHROOMS;
    public javax.swing.JLabel jLabel_Objective;
    public javax.swing.JLabel jLabel_POTIONS;
    public javax.swing.JLabel jLabel_ROCKS;
    public javax.swing.JLabel jLabel_Shelter;
    public javax.swing.JLabel jLabel_TOOLS;
    public javax.swing.JLabel jLabel_WOOD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_days;
    private javax.swing.JLabel lbl_durationdays;
    private javax.swing.JLabel lbl_durationdays1;
    private javax.swing.JLabel lbl_events;
    public javax.swing.JTextArea msg_Actions;
    public javax.swing.JTextField text_days;
    private javax.swing.JTextPane txt_durationDays;
    // End of variables declaration//GEN-END:variables
}
